[build]
    command = "yarn build"
    publish = "dist"

[[redirects]]
  from = "/2018-11-22-prettier-pre-commit/"
  to = "/blog/prettier-pre-commit/"

[[redirects]]
  from = "/2018-12-18-parcel-sass/"
  to = "/blog/parcel-sass/"

[[redirects]]
  from = "/2015-07-17-watch-compile-sass-npm/"
  to = "/blog/watch-compile-sass-npm/"

[[redirects]]
  from = "/2019-01-04-generate-blog-posts-gatsby-hygen/"
  to = "/blog/generate-blog-posts-with-hyphen/"

[[redirects]]
  from = "/2019-01-08-nodejs-windows-without-wsl/"
  to = "/blog/nodejs-windows-without-wsl/"

[[redirects]]
  from = "/2019-01-11-using-git-to-squash-commits-with-confidence/"
  to = "/blog/git-squash-commits-with-confidence/"

[[redirects]]
  from = "/2018-12-25-how-i-start-every-project/"
  to = "/blog/how-i-start-every-project/"